In [98]:
import seaborn as sns
data = sns.load_dataset('tips')

X = data.drop('total_bill', axis = 1)
y = data['tip'].astype('int')
# удаляем целевую переменную иначе overfitting
X = X.drop('tip', axis=1)

X.sample(10)

        sex smoker  day    time  size
103  Female    Yes  Sat  Dinner     2
44     Male     No  Sun  Dinner     4
11   Female     No  Sun  Dinner     4
175    Male    Yes  Sun  Dinner     2
97     Male    Yes  Fri  Dinner     2
56     Male    Yes  Sat  Dinner     4
231    Male    Yes  Sat  Dinner     3
222    Male    Yes  Fri   Lunch     1
95     Male    Yes  Fri  Dinner     4
36     Male     No  Sat  Dinner     3

In [99]:
# Дополните код для работы программы на месте троеточия "..."

import pandas as pd
from sklearn.model_selection import train_test_split
# Импортируйте энкодеры для предобработки категориальных переменных
from sklearn.preprocessing import OrdinalEncoder
# Импортируйте регрессор на дереве принятия решений
from sklearn.tree import DecisionTreeClassifier
# Импортируйте MAE
from sklearn.metrics import mean_squared_error as mse

# Предобработайте категориальные переменные в исходных данных (может быть более одной строки)
X = pd.get_dummies(X, columns=['sex', 'smoker', 'time'])
X['day'] = OrdinalEncoder().fit_transform(X[['day']])
# Разделите данные на тренировочную и тестовые выборки
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = .2, random_state = 42)
# Создайте и обучите регрессор на тренировочных данных
model = DecisionTreeClassifier()
model.fit(X_train, y_train)
# Сделайте предсказание на тренировочных данных
pred = model.predict(X_test)
# Вывести MAE до 3-го знака после запятой
print(f'{mse(y_test, pred):.4}')

1.347