In [138]:
import seaborn as sns
data = sns.load_dataset('tips')

X = data.drop('total_bill', axis = 1)
y = data['tip']
# удаляем целевую переменную иначе overfitting
X = X.drop('tip', axis=1)

X.sample(10)

        sex smoker   day    time  size
226  Female    Yes   Fri   Lunch     2
207    Male    Yes   Sat  Dinner     4
170    Male    Yes   Sat  Dinner     3
173    Male    Yes   Sun  Dinner     2
231    Male    Yes   Sat  Dinner     3
47     Male     No   Sun  Dinner     4
142    Male     No  Thur   Lunch     5
60     Male    Yes   Sat  Dinner     2
102  Female    Yes   Sat  Dinner     3
59     Male     No   Sat  Dinner     4

In [139]:
# Дополните код для работы программы на месте троеточия "..."

import pandas as pd
from sklearn.model_selection import train_test_split
# Импортируйте энкодеры для предобработки категориальных переменных
from sklearn.preprocessing import OrdinalEncoder
# Импортируйте регрессор на дереве принятия решений
from sklearn.tree import DecisionTreeRegressor
# Импортируйте MAE
from sklearn.metrics import mean_absolute_error as mae

# Предобработайте категориальные переменные в исходных данных (может быть более одной строки)
X = pd.get_dummies(X, columns=['sex', 'smoker', 'time'])
X['day'] = OrdinalEncoder().fit_transform(X[['day']])
# Разделите данные на тренировочную и тестовые выборки
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = .2, random_state = 42)
# Создайте и обучите регрессор на тренировочных данных
model = DecisionTreeRegressor()
model.fit(X_train, y_train)
# Сделайте предсказание на тренировочных данных
pred = model.predict(X_test)
# Вывести MAE до 3-го знака после запятой
print(f'{mae(y_test, pred):.4}')

1.029