In [14]:
import seaborn as sns
data = sns.load_dataset('tips')

X = data.drop('total_bill', axis = 1)
y = data['tip']
# удаляем целевую переменную иначе overfitting
X = X.drop('tip', axis=1)

X.sample(10)

        sex smoker   day    time  size
140  Female     No  Thur   Lunch     2
87     Male     No  Thur   Lunch     2
137  Female     No  Thur   Lunch     2
160    Male     No   Sun  Dinner     4
46     Male     No   Sun  Dinner     2
103  Female    Yes   Sat  Dinner     2
231    Male    Yes   Sat  Dinner     3
193    Male    Yes  Thur   Lunch     2
70     Male     No   Sat  Dinner     2
235    Male     No   Sat  Dinner     2

In [15]:
# Дополните код для работы программы на месте троеточия "..."

import pandas as pd
from sklearn.model_selection import train_test_split
# Импортируйте энкодеры для предобработки категориальных переменных
from sklearn.preprocessing import OrdinalEncoder
# Импортируйте регрессор на дереве принятия решений
from sklearn.tree import DecisionTreeRegressor
# Импортируйте MAE
from sklearn.metrics import mean_absolute_error as mae
from sklearn.metrics import mean_squared_error as mse

# Предобработайте категориальные переменные в исходных данных (может быть более одной строки)
X = pd.get_dummies(X, columns=['sex', 'smoker', 'time'])
X['day'] = OrdinalEncoder().fit_transform(X[['day']])
# Разделите данные на тренировочную и тестовые выборки
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = .2, random_state = 42)
# Создайте и обучите регрессор на тренировочных данных
model = DecisionTreeRegressor()
model.fit(X_train, y_train)
# Сделайте предсказание на тренировочных данных
pred = model.predict(X_test)
# Вывести MAE до 3-го знака после запятой
print(f'mean={y_test.mean():.4}, mae={mae(y_test, pred):.4}, rmse={mse(y_test, pred)**.5:.4}')

mean=2.642, mae=1.044, rmse=1.327